In [108]:
import numpy as np
import pandas as pd

In [109]:
df = pd.read_csv("C:\\Users\\libin_urv2w13\\Desktop\\mljourney\\Feature-Engineering\\Data.csv.xls")

In [110]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [111]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [112]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")
X.iloc[:,1:3] = imputer.fit_transform(X.iloc[:,1:3])

In [113]:
X

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

In [114]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer([("encoder",OneHotEncoder(),[0])],remainder="passthrough") # passthrough shows all columns
X=pd.DataFrame(ct.fit_transform(X))

In [115]:
X

0    1    2          3             4
0  1.0  0.0  0.0  44.000000  72000.000000
1  0.0  0.0  1.0  27.000000  48000.000000
2  0.0  1.0  0.0  30.000000  54000.000000
3  0.0  0.0  1.0  38.000000  61000.000000
4  0.0  1.0  0.0  40.000000  63777.777778
5  1.0  0.0  0.0  35.000000  58000.000000
6  0.0  0.0  1.0  38.777778  52000.000000
7  1.0  0.0  0.0  48.000000  79000.000000
8  0.0  1.0  0.0  50.000000  83000.000000
9  1.0  0.0  0.0  37.000000  67000.000000

In [116]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [117]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [118]:
X_train

0    1    2          3             4
1  0.0  0.0  1.0  27.000000  48000.000000
8  0.0  1.0  0.0  50.000000  83000.000000
3  0.0  0.0  1.0  38.000000  61000.000000
7  1.0  0.0  0.0  48.000000  79000.000000
4  0.0  1.0  0.0  40.000000  63777.777778
6  0.0  0.0  1.0  38.777778  52000.000000
2  0.0  1.0  0.0  30.000000  54000.000000
9  1.0  0.0  0.0  37.000000  67000.000000

In [119]:
Y_train

array([1, 0, 0, 1, 1, 0, 0, 1])

In [120]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_train

array([[-0.57735027, -0.77459667,  1.29099445, -1.57863608, -1.31838474],
       [-0.57735027,  1.29099445, -0.77459667,  1.55216793,  1.66395776],
       [-0.57735027, -0.77459667,  1.29099445, -0.08129503, -0.21065753],
       [ 1.73205081, -0.77459667, -0.77459667,  1.2799241 ,  1.32311862],
       [-0.57735027,  1.29099445, -0.77459667,  0.19094879,  0.02603632],
       [-0.57735027, -0.77459667,  1.29099445,  0.02457757, -0.9775456 ],
       [-0.57735027,  1.29099445, -0.77459667, -1.17027034, -0.80712603],
       [ 1.73205081, -0.77459667, -0.77459667, -0.21741694,  0.30060119]])