In [18]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [19]:
df = pd.read_csv("C:\\Users\\libin_urv2w13\\Desktop\\mljourney\\Feature-Engineering\\student_data.csv")

In [20]:
df.shape

(5000, 15)

In [21]:
df.isnull().sum()

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [22]:
df.dtypes

StudentID              int64
Age                    int64
Gender                 int64
Ethnicity              int64
ParentalEducation      int64
StudyTimeWeekly        int64
Absences               int64
Tutoring               int64
ParentalSupport        int64
Extracurricular        int64
Sports                 int64
Music                  int64
Volunteering           int64
GPA                  float64
GradeClass             int64
dtype: object

In [23]:
df["GPA"]=df["GPA"].astype("int")

In [24]:
df.dtypes

StudentID            int64
Age                  int64
Gender               int64
Ethnicity            int64
ParentalEducation    int64
StudyTimeWeekly      int64
Absences             int64
Tutoring             int64
ParentalSupport      int64
Extracurricular      int64
Sports               int64
Music                int64
Volunteering         int64
GPA                  int64
GradeClass           int64
dtype: object

In [25]:
df.drop(columns="StudentID",inplace=True)

In [26]:
df.head()

Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  Absences  \
0   17       1          1                  3               16        13   
1   18       1          2                  0               17        28   
2   15       1          0                  1               13        18   
3   17       1          0                  3                6         4   
4   17       0          1                  2                6        20   

   Tutoring  ParentalSupport  Extracurricular  Sports  Music  Volunteering  \
0         0                2                0       0      0             0   
1         0                2                1       1      1             0   
2         1                4                0       0      0             1   
3         0                3                1       0      0             0   
4         0                4                0       0      0             0   

   GPA  GradeClass  
0    3           1  
1    2           2  
2    3           0  
3    3           1  
4    3           1

In [27]:
# setting independent and dependent variables X and Y
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]

In [28]:
X

Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  Absences  \
0      17       1          1                  3               16        13   
1      18       1          2                  0               17        28   
2      15       1          0                  1               13        18   
3      17       1          0                  3                6         4   
4      17       0          1                  2                6        20   
...   ...     ...        ...                ...              ...       ...   
4995   15       0          3                  2               12        22   
4996   16       0          1                  2                1         2   
4997   17       1          1                  3               18        18   
4998   16       0          2                  2               15         0   
4999   18       1          2                  4                4        23   

      Tutoring  ParentalSupport  Extracurricular  Sports  Music  Volunteering  \
0            0                2                0       0      0             0   
1            0                2                1       1      1             0   
2            1                4                0       0      0             1   
3            0                3                1       0      0             0   
4            0                4                0       0      0             0   
...        ...              ...              ...     ...    ...           ...   
4995         0                2                0       1      1             0   
4996         0                2                0       1      0             0   
4997         1                0                1       0      0             1   
4998         0                2                1       1      1             0   
4999         0                0                1       0      0             1   

      GPA  
0       3  
1       2  
2       3  
3       3  
4       3  
...   ...  
4995    4  
4996    2  
4997    4  
4998    4  
4999    2  

[5000 rows x 13 columns]

In [29]:
Y

0       1
1       2
2       0
3       1
4       1
       ..
4995    0
4996    2
4997    0
4998    0
4999    3
Name: GradeClass, Length: 5000, dtype: int64

In [30]:
! pip install scikit-learn

In [31]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
xscale =scaler.fit_transform(X)
xscale


array([[0.66666667, 1.        , 0.33333333, ..., 0.        , 0.        ,
        0.5       ],
       [1.        , 1.        , 0.66666667, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 1.        ,
        0.5       ],
       ...,
       [0.66666667, 1.        , 0.33333333, ..., 0.        , 1.        ,
        1.        ],
       [0.33333333, 0.        , 0.66666667, ..., 1.        , 0.        ,
        1.        ],
       [1.        , 1.        , 0.66666667, ..., 0.        , 1.        ,
        0.        ]], shape=(5000, 13))

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(xscale,Y,test_size=0.2)

In [34]:
X_train

array([[0.        , 0.        , 0.66666667, ..., 0.        , 1.        ,
        0.        ],
       [0.33333333, 1.        , 0.66666667, ..., 0.        , 0.        ,
        1.        ],
       [0.33333333, 1.        , 0.        , ..., 0.        , 0.        ,
        0.5       ],
       ...,
       [1.        , 0.        , 0.66666667, ..., 1.        , 1.        ,
        0.        ],
       [0.33333333, 0.        , 0.33333333, ..., 0.        , 0.        ,
        0.5       ],
       [0.66666667, 1.        , 0.        , ..., 0.        , 1.        ,
        0.5       ]], shape=(4000, 13))

In [35]:
X_test

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.5       ],
       [0.66666667, 1.        , 0.33333333, ..., 0.        , 0.        ,
        0.5       ],
       [0.33333333, 0.        , 0.33333333, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [1.        , 0.        , 0.33333333, ..., 0.        , 0.        ,
        1.        ],
       [0.33333333, 1.        , 0.33333333, ..., 1.        , 0.        ,
        0.5       ],
       [1.        , 1.        , 0.        , ..., 0.        , 1.        ,
        0.5       ]], shape=(1000, 13))